[package]
name = "rust_sample"
version = "0.1.0"
authors = ["垣井駿努 <syunto07ka@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
